{% set version = "0.50.13" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tmod
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tmod_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tmod/tmod_{{ version }}.tar.gz
  sha256: 3dde8e55f63de1bb0dfcd9696ebd7a9699f44c5573aff1a2f234923ff78a0a98

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
    - r-xml
    - r-beeswarm
    - r-ggplot2
    - r-ggrepel
    - r-gplots
    - r-pheatmap
    - r-plotwidgets
    - r-purrr
    - r-rlang
    - r-tagcloud
    - r-tibble
    - r-tidyr
    - r-tidyselect
  run:
    - r-base
    - r-rcolorbrewer
    - r-xml
    - r-beeswarm
    - r-ggplot2
    - r-ggrepel
    - r-gplots
    - r-pheatmap
    - r-plotwidgets
    - r-purrr
    - r-rlang
    - r-tagcloud
    - r-tibble
    - r-tidyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('tmod')"           # [not win]
    - "\"%R%\" -e \"library('tmod')\""  # [win]

about:
  home: http://bioinfo.mpiib-berlin.mpg.de/tmod/
  license: GPL-2.0-or-later
  summary: Methods and feature set definitions for feature or gene set enrichment analysis in transcriptional and metabolic profiling data. Package includes tests for enrichment based on ranked lists of features, functions for visualisation and multivariate functional analysis.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - PertuyF

# Package: tmod
# Type: Package
# Title: Feature Set Enrichment Analysis for Metabolomics and Transcriptomics
# Version: 0.40
# Date: 2018-11-28
# Author: January Weiner
# Maintainer: January Weiner <january.weiner@gmail.com>
# Description: Methods and feature set definitions for feature or gene set enrichment analysis in transcriptional and metabolic profiling data. Package includes tests for enrichment based on ranked lists of features, functions for visualisation and multivariate functional analysis.
# License: GPL (>= 2.0)
# Depends: R (>= 2.10)
# LazyData: false
# VignetteBuilder: knitr
# URL: http://bioinfo.mpiib-berlin.mpg.de/tmod/
# Imports: beeswarm,tagcloud,XML,methods,plotwidgets
# Suggests: testthat,knitr,rmarkdown,pca3d,limma
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2018-11-29 12:48:59 UTC; january
# Repository: CRAN
# Date/Publication: 2018-11-29 13:10:03 UTC
