appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Rayf81Q/oTlKcqh4wcDmzxHezvq7WQkz7SYnYqI76uQNtOVC2Yw0kkNg/Jadu72Sx9Qsn8aymVd+P2IeYXOaVJD+ilQJ3wGP6EOML82h4QI10kSH5m3y2NzIdptgghybuV6i7dQTlbYZ1zb1qxMbzT7cCimZclI/AZLWbP98QN4Dss79SnS50GY9BbycT3EZ13k6Aasdz+eDGmcl1GsAZl+C3LPW9C+6qcGbflun8+uVBuvF3XYeKzyE+77OdxRUxWT8Ql7XN4ngLzgCgAJmao7j/AbhswHroM8GjAGnQIoNNyiMhWE7p42uUvMYTHMa2/GUZgR/l8aoeXKWN/ldml58cqczXTgp07mg/S6OFeU91bqI7VEtftjF+dqrJ46fEMHy+CVDT89tOpnL0Yu0X8qgMU8/HFzbd9MSrXsIY32k4UIcCufk5bTuiDJp1XL8/4MP6WycOjUSqyDKMolSsO1IHSwv7WW/ionW2Ewjt946XNBAIiQUuZjYNCSrYXKxnnitpj2KeBgsJHe64kbIGg9GVqa+sAuamyB7r0glLBHibnh8l9a4aZhlRDsoAikHrKR6RsOHLVLYtnHAVd4A5sfnE+q4PcKgeJ2iPZj2eOPmjelmheHStaStFkKYI29Mwka6ukVeEDtNdD2yXf2RD6eTSirCioxcLHu+NKUNnto=
